### ISSUE TITLE
Latest pep257 breaks this.

### ISSUE THREAD

**Issue by Robpol86** [Robpol86/flake8-pep257#4]
```
Traceback (most recent call last):
    File "/mnt/jenkins/workspace/test-flask-thing/env/bin/flake8", line 9, in <module>
      load_entry_point('flake8==2.4.1', 'console_scripts', 'flake8')()
    File "/mnt/jenkins/workspace/test-flask-thing/env/local/lib/python2.7/site-packages/flake8/main.py", line 25, in main
      flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
    File "/mnt/jenkins/workspace/test-flask-thing/env/local/lib/python2.7/site-packages/flake8/engine.py", line 126, in get_style_guide
      options_hook(options)
    File "/mnt/jenkins/workspace/test-flask-thing/env/local/lib/python2.7/site-packages/flake8_pep257.py", line 81, in parse_options
      opt_parser = pep257.get_option_parser()
  AttributeError: 'module' object has no attribute 'get_option_parser'
```

**Comment by wcooley** [comment]
Specifically, _pep257_ **0.7.0** breaks _flake8-pep257_ **1.0.3**, because _pep257_ removed the module-level `get_option_parser` function.

_pep257_ **0.6.0** works.

_pep257_ **0.3.2**, which one might have installed because _pytest-pep257_ requires it, also does not have the `get_option_parser` function.

I'm adding this just in case someone else was trying to figure out what is currently required to get it to work.

**Comment by Arcanemagus** [comment]
@Robpol86 any chance you can get this fixed? For the moment I'm going to be removing this from the list of recommended pep257 `flake8` plugins on the [`linter-flake8`](https://github.com/AtomLinter/linter-flake8) Atom package until this can be fixed.

**Comment by Robpol86** [comment]
Sorry I've been working on a couple of other things. I'll fix this this weekend.
